In [1]:
#### Import relevant python packages ####
import numpy as np
import matplotlib.pyplot as plt

# Vectors in numpy #

### The 1-dimensional numpy array ###

Below I have an equality of vector $\vec{v}$ to the following numerical values that make up vector:

$$\vec{v} = [v_1, v_2, v_3]$$


$$ \vec{v} = [ 7 , 7 , 3 ] $$

In numpy you can create and store a vector using a numpy array using the syntax in the cell below:

In [7]:
v = np.array([7,7,3])

### Vector operations in numpy ###

#### The Dot product ####

$$ d = \vec{v} \cdot \vec{u} $$

The above equation is equivalent to the following below:

$$ d = v_1 \times u_1 + v_2 \times u_2 + v_3 \times u_3 $$

Which can be performed in python using the syntax in the cell below (after first defining the $\vec{u}$):

In [8]:
u = np.array([1,1,1])

In [9]:
d = np.dot(v,u)
print(d)

17


Note the data type of d. The dot product between two vectors produces a 'scalar' value

#### The Vector Product ####

$$ \vec{w} = \vec{v} \times \vec{u} $$

Note that $\vec{w}$ has the tiny arrow above the w which is an early indication that $\vec{w}$ is going to be a vector

Which is usually equivalent to the equation below:

$$
\vec{w} =\begin{bmatrix} v_{1} \\ v_{2} \\ v_{3} \end{bmatrix} \times \begin{bmatrix} u_{1} \\ u_{2} \\ u_{3} \end{bmatrix}
$$

and more explicitly:

$$ \vec{w} = \begin{bmatrix} (v_2*u_3 - u_2*v_3) \\ -(v_1*u_3 - u_1*v_3) \\ (v_1*u_2 - v_2*u_1) \end{bmatrix} $$

Which can be performed in python using the syntax in the cell below:

In [22]:
w = np.cross(v,u)
print(w)

[ 4 -4  0]


A characteristic of the cross product is the operation of a vector on itself yields a zero vector:

$$\vec{v} \times \vec{v} = 0$$

This is demonstrated below using the python/numpy syntax:

In [6]:
v_cross_v = np.cross(v,v)
print(v_cross_v)

[0 0 0]


# Matrices in numpy #

## The 2 dimensional numpy array ##

Below I have an equality of matrix $M$ to the following numerical values that it is composed of:

$$ M = \begin{bmatrix} m_{11} & m_{12} & m_{13} \\ m_{21} & m_{22} & m_{23} \\ m_{31} & m_{32} & m_{33} \end{bmatrix} $$

$$ M = \begin{bmatrix} \sqrt{2}/2 & -\sqrt{2}/2 & 0 \\ \sqrt{2}/2 & \sqrt{2}/2 & 0 \\ 0 & 0 & 1 \end{bmatrix} $$

In numpy you can create and store a matrix using a numpy array using the syntax in the cell below:

In [24]:
M = np.array([[np.sqrt(2.0)/2.0, -np.sqrt(2.0)/2.0, 0], [np.sqrt(2.0)/2.0, np.sqrt(2.0)/2.0, 0], [0,0,1.0]])
print(M)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


I'll also create a matrix $N$ to demonstrate some operations:

$$ N = \begin{bmatrix} n_{11} & n_{12} & n_{13} \\ n_{21} & n_{22} & n_{23} \\ n_{31} & n_{32} & n_{33} \end{bmatrix} $$

$$ N = \begin{bmatrix} \sqrt{3}/2 & -1/2 & 0 \\ 1/2 & \sqrt{3}/2 & 0 \\ 0 & 0 & 1 \end{bmatrix} $$

In [28]:
N = np.array([[np.sqrt(3.0)/2.0, -1.0/2.0, 0], [1.0/2.0, np.sqrt(3.0)/2.0, 0], [0,0,1.0]])
print(N)

[[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]


## Multiplying Matrices

$$ M \times N = \begin{bmatrix} m_{11} & m_{12} & m_{13} \\ m_{21} & m_{22} & m_{23} \\ m_{31} & m_{32} & m_{33} \end{bmatrix} \times \begin{bmatrix} n_{11} & n_{12} & n_{13} \\ n_{21} & n_{22} & n_{23} \\ n_{31} & n_{32} & n_{33} \end{bmatrix}$$


$$
M \times N = \begin{bmatrix} 
(m_{11}*n_{11} + m_{12}*n_{21} + m_{13}*n_{31}) & (m_{11}*n_{12} + m_{12}*n_{22} + m_{13}*n_{32}) & (m_{11}*n_{13} + m_{12}*n_{23} + m_{13}*n_{33}) \\ (m_{21}*n_{11} + m_{22}*n_{21} + m_{23}*n_{31}) & (m_{21}*n_{12} + m_{22}*n_{22} + m_{23}*n_{32}) & (m_{21}*n_{13} + m_{22}*n_{23} + m_{23}*n_{33}) \\
(m_{31}*n_{11} + m_{32}*n_{21} + m_{33}*n_{31}) & (m_{31}*n_{12} + m_{32}*n_{22} + m_{33}*n_{32}) & (m_{31}*n_{13} + m_{32}*n_{23} + m_{33}*n_{33})
\end{bmatrix}
$$

In [35]:
M_times_N = np.dot(M,N)
M_times_N

array([[ 0.25881905, -0.96592583,  0.        ],
       [ 0.96592583,  0.25881905,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

#### The above matrices (N, M, and M_times_N) are actually examples of the application of the Rotation Matrix (R) in a 2 dimensional plane.

#### In this particular case, it represents a rotation by an angle $\theta$, of a 3-D cartesian vector [x,y.z] in the X-Y plane (about the z-axis):


$$ R(\theta) = \begin{bmatrix} \mathrm{cos}(\theta) & -\mathrm{sin}(\theta) & 0 \\ \mathrm{sin}(\theta) & \mathrm{cos}(\theta) & 0 \\ 0 & 0 & 1 \end{bmatrix} $$

#### You can see by the form of $R(\theta)$ that R is a function of $\theta$

#### We can generalize this function in python by making a function of our own without having to seperately compute and type up each time:

In [65]:
def rotation(theta):
    return np.array([[np.round(np.cos(theta)), -np.round(np.sin(theta)), 0], [np.round(np.sin(theta)), np.round(np.cos(theta)), 0], [0, 0, 1]])

Let's test it out on a 90 [degree] rotation, or \pi/2 [rad]:

In [66]:
rotation(np.pi/2.0)

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])

## Problem Set

### (Problem 1)

#### Compute the dot and the cross product of between all possible vector pairs of a, b, and c:

$$a = [3,9.2]$$
$$b = [7,1,8]$$
$$c = [1,6,5]$$

#### Compute these operations by hand and using python
#### Make sure you also consider the reverse orders of all operation pairs and consider the following questions:
#### Did the forward and reverse order of the operations equal each other?
#### Are these operations Commutative?




### (Problem 2)
#### Multiply matrices M and N by hand and verify the result produced in numpy by np.dot(M,N)

### (Problem 3)

#### Within the rotation function made just above, there is a function called np.round(). Do a quick search of the numpy documentation and see what it does. You usually can search for it in google or bing by just typing in the search bar "numpy.round"

#### (Problem 4)

#### The matrices M, N, and M_times_N are all rotation matrices, what rotation angles to they respectively apply? (Hint: You can use np.arccos() or np.arcsin() to help out and you can respond in radians or degrees but be sure to identify the unit, whichever one chosen.